### ISSUE TITLE
[Q] CDN?

### ISSUE THREAD

**Issue by xplshn** [zshall/shell-css#4]

**Comment by zshall** [comment]
You can use JsDelivr. Here's an example:

~~~html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/shell-css@1.1.0/dist/shell.css">
~~~

This should be added to the documentation site though so I'll do this in this issue.

**Comment by xplshn** [comment]
thanks! I know nothing about web development..., Will you document this more, kind of like 98.css?

**Comment by zshall** [comment]
@xplshn I haven't seen 98.css before but I just looked it over and that gives me some good ideas, especially considering issue #3 . An issue I haven't written yet about this project is to create some sort of web component library so that different shell components could be written like `<window title="Some window"></window>` rather than `<div class="window"><div class="title-bar">Some window</div></div>` and we could standardize things across different web frameworks. This would probably become an additional, optional feature.

I'll make an issue for improving examples and documentation. At present this project is more like a collection of CSS classes that *can* be used, rather than specifying *how* they should be used. I used Bootstrap Grid in the documentation site to make everything flow nicely but I tried to leave it up to users to decide which tooling is best for them.

If you've got a specific project in mind and would like some assistance, I've started a chat room over on [Slack](https://join.slack.com/t/greenhillplaza/shared_invite/zt-2dq8mx6sm-3YnobHETTmxUNE02TOSPRg) in the #shell-css channel where myself and other community members can help with specific questions and implementation details regarding your usage of it.

I've updated the documentation and the `README` with CDN details so I'll close this issue. Feel free to reopen or comment further if something doesn't work regarding the CDN.

**Comment by xplshn** [comment]
Okay, that's all great to hear. I am not familiar with web tooling, so for the time being I'll try to use this CSS framework a little in my website, which is hosted in neocities, so, I don't know how it'll go, since its a static website I can't do much.

**Comment by zshall** [comment]
Ah I use Neocities as well! The docs site actually is hosted there. Depending on the type of project Static Site Generators are pretty useful sometimes.

But yeah if you have any questions feel free to reach out and I’ll do my best to help!
